### ISSUE TITLE
Suggestion: Send reminders via Direct Messages, with resend timer

### ISSUE THREAD

**Issue by rnelson0** [hangops/hangops-jobbot#40]
During testing, we see that hangbot is sending messages to the users in the channel they are in. This can be somewhat noisy. The first, and probably easier issue to resolve is, ensure that responses to a user are only sent once per X seconds. If someone posts two job listings one right after the other, they shouldn't get two reminders. One per day is probably OK.

Second, send the response via Direct Message. Example code to do so can be seen at https://github.com/slackapi/hubot-slack/issues/332#issuecomment-246759358. I feel that this disturbs the channel's flow less, but still lets the poster get a helpful message.

**Comment by rrxtns** [comment]
Could probably swipe some ideas from here regarding "remembering" the last time we replied to someone: [https://github.com/github/hubot-scripts/blob/master/src/scripts/remember.coffee](https://github.com/github/hubot-scripts/blob/master/src/scripts/remember.coffee)

**Comment by sntxrr** [comment]
I went the "reply in threads route" - closed with [#78](https://github.com/hangops/hangops-jobbot/pull/78)
